name:                pandocAPI
version:             0.1.0.0
github:              "hgflimited/pandocAPI"
license:             MIT
author:              "Patrick Henderson"
maintainer:          "phenderson@hgf.com"
copyright:           "2020 HGF Limited"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hgflimited/pandocAPI#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- directory
- pandoc
- http-types
- resourcet
- text
- mime-types
- wai
- wai-extra
- warp

library:
  source-dirs: src

executables:
  pandocAPI-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandocAPI

tests:
  pandocAPI-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandocAPI
